const unit_1 = [
    {Eng: 'bag',Ru:'Сумка'},
    {Eng: 'book',Ru:'Книга'},
    {Eng: 'camera',Ru:'Камера'},
    {Eng: 'car',Ru:'Машина'},
    {Eng: 'computer',Ru:'Компютер'},
    {Eng: 'fine',Ru:'Отлично'},
    {Eng: 'hamburger',Ru:'Гамбургер'},
    {Eng: 'hello',Ru:'Здраствуйте'},
    {Eng: 'hi',Ru:'Здраствуйте'},
    {Eng: 'house',Ru:'Дом'},
    {Eng: 'How are you',Ru:'Как ваши дела'},
    {Eng: 'name',Ru:'Имя'},
    {Eng: 'number',Ru:'Число'},
    {Eng: 'photograph',Ru:'Фотография'},
    {Eng: 'sandwich',Ru:'Сэндвич'},
    {Eng: 'student',Ru:'Студент'},
    {Eng: 'television',Ru:'Телевизор'},
    {Eng: 'thanks',Ru:'Спасибо'},
    {Eng: 'this',Ru:'Это'},
    {Eng: 'wery well',Ru:'Очень хорошо'},
    {Eng: 'what',Ru:'ЧТо'},
    {Eng: 'my',Ru:'Мой'},
    {Eng: 'his',Ru:'Его'},
    {Eng: 'her',Ru:'Ее'},
    {Eng: 'its',Ru:'Его'},
    {Eng: 'our',Ru:'Наш'},
    {Eng: 'your',Ru:'Ваш'},
    {Eng: 'their',Ru:'Их'},  
]

export default unit_1;